# Generated by Django 4.2.5 on 2023-10-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0007_alter_comments_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20),
        ),
    ]
