# Generated by Django 4.2.5 on 2023-10-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0009_rename_autor_comments_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacionComment', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20)),
            ],
        ),
    ]
