# Generated by Django 4.2.5 on 2023-10-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0010_puntuacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='puntuacion',
        ),
    ]
